import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { extractEnvKeys } from "./extract-env-schema.js";
import { syncDotenvContent } from "./dotenv.js";
import type { EnvKey } from "../types.js";

export interface SyncResult {
  envExampleChanged: boolean;
  dotEnvChanged: boolean;
  warnings: string[];
  errors: string[];
}

export function runSync(cwd: string): SyncResult {
  const keys = extractEnvKeys(cwd);
  const envExamplePath = resolve(cwd, "env.example");
  const dotEnvPath = resolve(cwd, ".env");

  const nextEnvExample = buildEnvExample(keys);
  const currentEnvExample = existsSync(envExamplePath) ? normalize(readFileSync(envExamplePath, "utf8")) : "";
  const envExampleChanged = currentEnvExample !== nextEnvExample;

  if (envExampleChanged) {
    writeFileSync(envExamplePath, nextEnvExample, "utf8");
  }

  const currentDotEnv = existsSync(dotEnvPath) ? readFileSync(dotEnvPath, "utf8") : "";
  const dotEnvResult = syncDotenvContent(currentDotEnv, keys);

  if (dotEnvResult.hasChanges) {
    writeFileSync(dotEnvPath, dotEnvResult.nextContent, "utf8");
  }

  return {
    envExampleChanged,
    dotEnvChanged: dotEnvResult.hasChanges,
    warnings: dotEnvResult.warnings,
    errors: dotEnvResult.unresolvedErrors,
  };
}

export function buildEnvExample(keys: EnvKey[]): string {
  const server = keys.filter((key) => key.scope === "server");
  const client = keys.filter((key) => key.scope === "client");

  const lines: string[] = [
    "# Generated by env-sync from src/env.ts.",
    "# Do not edit manually. Run: env-sync sync",
    "",
  ];

  if (server.length > 0) {
    lines.push("# Server");
    for (const key of server) {
      lines.push(`${key.key}=`);
    }
    lines.push("");
  }

  if (client.length > 0) {
    lines.push("# Client");
    for (const key of client) {
      lines.push(`${key.key}=`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function normalize(text: string): string {
  let value = text.replace(/\r\n/g, "\n");
  if (!value.endsWith("\n")) {
    value += "\n";
  }
  return value;
}
